name: Periodic Health Check

on:
  schedule:
    - cron: '*/2 * * * *'

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Ping /health
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://paraspokedex.fly.dev/periodi
#ping /periodic every 2 minutes         